### ISSUE TITLE
管理后台无法登陆过去

### ISSUE THREAD

**Issue by liduchuan** [romejiang/fastshort#3]
<img width="1191" alt="image" src="https://github.com/romejiang/fastshort/assets/115539090/501b323c-fe5c-49f9-b4b0-c0e2b8a16eb1">

**Comment by Weijia0Li** [comment]
问题+1，你解决了吗

**Comment by Ikaros-521** [comment]
+1

**Comment by ElevenKong** [comment]
我也遇到这个问题，解决了的大佬帮忙解答一下

**Comment by azwhale** [comment]
https://github.com/romejiang/fastshort/issues/7#issuecomment-2113910450
